[[main]]
  identifier = "posts"
  name       = "文章"
  pageRef    = "posts"
  weight     = 10

[[main]]
  identifier = "about"
  name       = "关于我"
  pageRef    = "about"
  weight     = 100

# 不再添加 docs / samples / archives 等 demo 项